# Codecov configuration for CSFrace Scraper Backend
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 85%
        threshold: 1%

  ignore:
    - "tests/"
    - "alembic/"
    - "docker/"
    - "scripts/"
    - "**/__pycache__/"
    - "**/*.pyc"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

component_management:
  default_rules:
    flag_regexes:
      - name: core
        paths:
          - "src/core/"
      - name: database
        paths:
          - "src/database/"
      - name: api
        paths:
          - "src/api/"
      - name: auth
        paths:
          - "src/auth/"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: "project"
        target: 85%
      - type: "patch"
        target: 85%