global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: csfrace-scraper
  metrics_path: /health/prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:9090
