"""add_user_settings_table

Revision ID: f21b6337b3fe
Revises: cdbc0216f3da
Create Date: 2025-09-20 02:40:16.762165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f21b6337b3fe"
down_revision: Union[str, Sequence[str], None] = "cdbc0216f3da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_images_content_id"), table_name="images")
    op.drop_index(op.f("idx_images_downloaded"), table_name="images")
    op.drop_index(op.f("idx_images_original_url"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("idx_batches_created_at"), table_name="batches")
    op.drop_index(op.f("idx_batches_status"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("idx_content_job_id"), table_name="content")
    op.drop_index(op.f("idx_content_json"), table_name="content", postgresql_using="gin")
    op.drop_index(op.f("idx_content_published_at"), table_name="content")
    op.drop_index(op.f("idx_content_search"), table_name="content", postgresql_using="gin")
    op.drop_index(op.f("idx_content_shopify_handle"), table_name="content")
    op.drop_index(op.f("idx_content_slug"), table_name="content")
    op.drop_index(op.f("idx_content_title"), table_name="content")
    op.drop_index(op.f("idx_content_wordpress_id"), table_name="content")
    op.drop_table("content")
    op.drop_index(op.f("idx_cache_expires_at"), table_name="cache")
    op.drop_index(op.f("idx_cache_key"), table_name="cache")
    op.drop_index(op.f("idx_cache_url"), table_name="cache")
    op.drop_table("cache")
    op.alter_column(
        "jobs", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "jobs",
        "job_type",
        existing_type=postgresql.ENUM("single", "batch", "scheduled", name="job_type"),
        server_default=None,
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "target_format",
        existing_type=postgresql.ENUM("html", "json", "markdown", "csv", name="export_format"),
        server_default=None,
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "processing", "completed", "failed", "cancelled", name="job_status"
        ),
        server_default=None,
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs", "priority", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.alter_column(
        "jobs", "retry_count", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.alter_column(
        "jobs", "max_retries", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.alter_column(
        "jobs",
        "options",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "jobs",
        "download_size_bytes",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "output_size_bytes",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs", "batch_id", existing_type=sa.UUID(), type_=sa.String(), existing_nullable=True
    )
    op.drop_index(op.f("idx_jobs_batch_id"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_created_at"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_metadata"), table_name="jobs", postgresql_using="gin")
    op.drop_index(op.f("idx_jobs_source_url"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_status"), table_name="jobs")
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.drop_constraint(op.f("jobs_batch_id_fkey"), "jobs", type_="foreignkey")
    op.create_foreign_key(None, "jobs", "users", ["user_id"], ["id"])
    op.drop_column("jobs", "metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("jobs_batch_id_fkey"), "jobs", "batches", ["batch_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.create_index(op.f("idx_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("idx_jobs_source_url"), "jobs", ["source_url"], unique=False)
    op.create_index(
        op.f("idx_jobs_metadata"), "jobs", ["metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_jobs_created_at"), "jobs", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(op.f("idx_jobs_batch_id"), "jobs", ["batch_id"], unique=False)
    op.alter_column(
        "jobs", "batch_id", existing_type=sa.String(), type_=sa.UUID(), existing_nullable=True
    )
    op.alter_column(
        "jobs",
        "output_size_bytes",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "download_size_bytes",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "jobs",
        "options",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "jobs",
        "max_retries",
        existing_type=sa.INTEGER(),
        server_default=sa.text("3"),
        nullable=True,
    )
    op.alter_column(
        "jobs",
        "retry_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
    )
    op.alter_column(
        "jobs", "priority", existing_type=sa.INTEGER(), server_default=sa.text("5"), nullable=True
    )
    op.alter_column(
        "jobs",
        "status",
        existing_type=sa.String(),
        server_default=sa.text("'pending'::job_status"),
        type_=postgresql.ENUM(
            "pending", "processing", "completed", "failed", "cancelled", name="job_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "target_format",
        existing_type=sa.String(),
        server_default=sa.text("'html'::export_format"),
        type_=postgresql.ENUM("html", "json", "markdown", "csv", name="export_format"),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "job_type",
        existing_type=sa.String(),
        server_default=sa.text("'single'::job_type"),
        type_=postgresql.ENUM("single", "batch", "scheduled", name="job_type"),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.create_table(
        "cache",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("cache_key", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("cache_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "headers", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hit_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_accessed",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cache_pkey")),
        sa.UniqueConstraint(
            "cache_key",
            name=op.f("cache_cache_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_cache_url"), "cache", ["url"], unique=False)
    op.create_index(op.f("idx_cache_key"), "cache", ["cache_key"], unique=False)
    op.create_index(op.f("idx_cache_expires_at"), "cache", ["expires_at"], unique=False)
    op.create_table(
        "content",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "content_type",
            postgresql.ENUM("wordpress", "shopify", "generic", name="content_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("html_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("markdown_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "json_content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("meta_title", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("meta_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("meta_keywords", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column("wordpress_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "wordpress_categories", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "wordpress_tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.Column("wordpress_author", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("shopify_handle", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "shopify_template_suffix", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "shopify_published",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="content_job_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="content_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_content_wordpress_id"), "content", ["wordpress_id"], unique=False)
    op.create_index(op.f("idx_content_title"), "content", ["title"], unique=False)
    op.create_index(op.f("idx_content_slug"), "content", ["slug"], unique=False)
    op.create_index(op.f("idx_content_shopify_handle"), "content", ["shopify_handle"], unique=False)
    op.create_index(
        op.f("idx_content_search"),
        "content",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(html_content, ''::text))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_content_published_at"),
        "content",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_content_json"), "content", ["json_content"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("idx_content_job_id"), "content", ["job_id"], unique=False)
    op.create_table(
        "batches",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "processing", "completed", "failed", "cancelled", name="job_status"
            ),
            server_default=sa.text("'pending'::job_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_jobs",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_jobs",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "failed_jobs",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "concurrent_limit",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rate_limit_per_second",
            sa.INTEGER(),
            server_default=sa.text("10"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="batches_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_batches_status"), "batches", ["status"], unique=False)
    op.create_index(
        op.f("idx_batches_created_at"),
        "batches",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "images",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("original_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("local_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cdn_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("mime_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("width", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("height", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("alt_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("caption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "downloaded",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "optimized",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.id"], name=op.f("images_content_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("images_pkey")),
    )
    op.create_index(op.f("idx_images_original_url"), "images", ["original_url"], unique=False)
    op.create_index(op.f("idx_images_downloaded"), "images", ["downloaded"], unique=False)
    op.create_index(op.f("idx_images_content_id"), "images", ["content_id"], unique=False)
    # ### end Alembic commands ###
