"""add start_time and end_time fields

Revision ID: ea6fb7cb28b0
Revises: 5131d00ba2c5
Create Date: 2025-08-27 01:43:17.799860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea6fb7cb28b0"
down_revision: Union[str, Sequence[str], None] = "5131d00ba2c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scraping_jobs", sa.Column("start_time", sa.Float(), nullable=True))
    op.add_column("scraping_jobs", sa.Column("end_time", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraping_jobs", "end_time")
    op.drop_column("scraping_jobs", "start_time")
    # ### end Alembic commands ###
