"""initial_schema_from_models

Revision ID: 81c6cf81eae0
Revises:
Create Date: 2025-10-09 06:53:15.024332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81c6cf81eae0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_lockouts",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique lockout record identifier",
        ),
        sa.Column(
            "user_id", sa.String(length=50), nullable=False, comment="User ID who is locked out"
        ),
        sa.Column(
            "username",
            sa.String(length=100),
            nullable=False,
            comment="Username for quick lookups and audit trail",
        ),
        sa.Column(
            "failed_attempts",
            sa.Integer(),
            nullable=False,
            comment="Current number of consecutive failed login attempts",
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False, comment="Current lockout status"),
        sa.Column(
            "lockout_reason",
            sa.String(length=100),
            nullable=True,
            comment="Reason for lockout (failed_attempts, suspicious_activity, admin_action)",
        ),
        sa.Column(
            "first_failed_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of first failed attempt in current sequence",
        ),
        sa.Column(
            "last_failed_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of most recent failed attempt",
        ),
        sa.Column(
            "locked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when account was locked",
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when lockout expires (NULL for permanent)",
        ),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when account was unlocked",
        ),
        sa.Column(
            "client_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address of failed login attempts",
        ),
        sa.Column(
            "user_agent", sa.Text(), nullable=True, comment="User agent of failed login attempts"
        ),
        sa.Column(
            "unlocked_by",
            sa.String(length=100),
            nullable=True,
            comment="Admin user who unlocked the account manually",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_lockouts_is_locked"), "account_lockouts", ["is_locked"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_locked_until"), "account_lockouts", ["locked_until"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_user_id"), "account_lockouts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_username"), "account_lockouts", ["username"], unique=False
    )
    op.create_table(
        "revoked_tokens",
        sa.Column(
            "jti",
            sa.String(length=100),
            nullable=False,
            comment="JWT ID claim - unique identifier for each token",
        ),
        sa.Column(
            "user_id",
            sa.String(length=50),
            nullable=True,
            comment="User who owned the token (for bulk revocation)",
        ),
        sa.Column(
            "token_type",
            sa.String(length=20),
            nullable=False,
            comment="Token type: access, refresh, or reset",
        ),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token was originally issued",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token naturally expires",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token was revoked",
        ),
        sa.Column(
            "revocation_reason",
            sa.String(length=100),
            nullable=True,
            comment="Reason for revocation: logout, password_change, admin_action, etc.",
        ),
        sa.Column(
            "revoked_by",
            sa.String(length=50),
            nullable=True,
            comment="Who/what revoked the token (user_id, admin_id, or system)",
        ),
        sa.Column(
            "client_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address when token was revoked",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="User agent when token was revoked",
        ),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_revoked_tokens_expires_at"), "revoked_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_revoked_tokens_user_id"), "revoked_tokens", ["user_id"], unique=False)
    op.create_table(
        "system_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_type", sa.String(length=100), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("string_value", sa.String(length=500), nullable=True),
        sa.Column("json_value", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("component", sa.String(length=100), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("tags", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_metrics_component"), "system_metrics", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_system_metrics_metric_type"), "system_metrics", ["metric_type"], unique=False
    )
    op.create_index(
        op.f("ix_system_metrics_timestamp"), "system_metrics", ["timestamp"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "webauthn_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("challenge_key", sa.String(length=255), nullable=False),
        sa.Column("challenge", sa.String(length=1024), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("challenge_type", sa.String(length=50), nullable=False),
        sa.Column("origin", sa.String(length=255), nullable=True),
        sa.Column("rp_id", sa.String(length=255), nullable=True),
        sa.Column("user_verification", sa.String(length=50), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webauthn_challenges_challenge_key"),
        "webauthn_challenges",
        ["challenge_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_challenge_type"),
        "webauthn_challenges",
        ["challenge_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_created_at"),
        "webauthn_challenges",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_expires_at"),
        "webauthn_challenges",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_user_id"), "webauthn_challenges", ["user_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column(
            "domain",
            sa.String(length=253),
            nullable=False,
            comment="Extracted domain from source_url for efficient statistics and filtering",
        ),
        sa.Column("target_format", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), server_default="{}", nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("download_size_bytes", sa.Integer(), nullable=True),
        sa.Column("output_size_bytes", sa.Integer(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_domain"), "jobs", ["domain"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_table(
        "linked_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_account_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "token_scopes",
            sa.Text(),
            nullable=True,
            comment="Comma-separated OAuth scopes for revocation tracking",
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", "provider_account_id", name="uq_user_provider_account"
        ),
    )
    op.create_index(
        op.f("ix_linked_accounts_user_id"), "linked_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("default_priority", sa.String(length=20), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("job_timeout", sa.Integer(), nullable=False),
        sa.Column("api_url", sa.String(length=255), nullable=False),
        sa.Column("api_timeout", sa.Integer(), nullable=False),
        sa.Column("refresh_interval", sa.Integer(), nullable=False),
        sa.Column("retry_attempts", sa.Integer(), nullable=False),
        sa.Column("enable_caching", sa.Boolean(), nullable=False),
        sa.Column("dark_mode", sa.Boolean(), nullable=False),
        sa.Column("show_job_ids", sa.Boolean(), nullable=False),
        sa.Column("compact_mode", sa.Boolean(), nullable=False),
        sa.Column("jobs_per_page", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("completion_alerts", sa.Boolean(), nullable=False),
        sa.Column("error_notifications", sa.Boolean(), nullable=False),
        sa.Column("browser_notifications", sa.Boolean(), nullable=False),
        sa.Column("custom_settings", sa.JSON(), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True)
    op.create_table(
        "webauthn_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("credential_id", sa.String(length=1024), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=100), nullable=True),
        sa.Column("attestation_object", sa.Text(), nullable=True),
        sa.Column("attestation_format", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("backup_eligible", sa.Boolean(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("registration_ip", sa.String(length=45), nullable=True),
        sa.Column("registration_user_agent", sa.Text(), nullable=True),
        sa.Column("last_used_ip", sa.String(length=45), nullable=True),
        sa.Column("last_used_user_agent", sa.Text(), nullable=True),
        sa.Column("security_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webauthn_credentials_credential_id"),
        "webauthn_credentials",
        ["credential_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_is_active"),
        "webauthn_credentials",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_last_used_at"),
        "webauthn_credentials",
        ["last_used_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_user_id"), "webauthn_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "content_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("original_html", sa.Text(), nullable=True),
        sa.Column("converted_html", sa.Text(), nullable=True),
        sa.Column("shopify_html", sa.Text(), nullable=True),
        sa.Column("html_file_path", sa.String(length=1024), nullable=True),
        sa.Column("metadata_file_path", sa.String(length=1024), nullable=True),
        sa.Column("images_directory", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("og_title", sa.String(length=500), nullable=True),
        sa.Column("og_description", sa.Text(), nullable=True),
        sa.Column("og_image", sa.String(length=1024), nullable=True),
        sa.Column("twitter_card", sa.String(length=50), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("image_count", sa.Integer(), nullable=True),
        sa.Column("link_count", sa.Integer(), nullable=True),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("conversion_stats", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_results_job_id"), "content_results", ["job_id"], unique=False)
    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=True),
        sa.Column("operation", sa.String(length=100), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("exception_traceback", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_logs_job_id"), "job_logs", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_logs_level"), "job_logs", ["level"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_logs_level"), table_name="job_logs")
    op.drop_index(op.f("ix_job_logs_job_id"), table_name="job_logs")
    op.drop_table("job_logs")
    op.drop_index(op.f("ix_content_results_job_id"), table_name="content_results")
    op.drop_table("content_results")
    op.drop_index(op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_last_used_at"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_is_active"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_credential_id"), table_name="webauthn_credentials")
    op.drop_table("webauthn_credentials")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_linked_accounts_user_id"), table_name="linked_accounts")
    op.drop_table("linked_accounts")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_domain"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_webauthn_challenges_user_id"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_expires_at"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_created_at"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_challenge_type"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_challenge_key"), table_name="webauthn_challenges")
    op.drop_table("webauthn_challenges")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_metrics_timestamp"), table_name="system_metrics")
    op.drop_index(op.f("ix_system_metrics_metric_type"), table_name="system_metrics")
    op.drop_index(op.f("ix_system_metrics_component"), table_name="system_metrics")
    op.drop_table("system_metrics")
    op.drop_index(op.f("ix_revoked_tokens_user_id"), table_name="revoked_tokens")
    op.drop_index(op.f("ix_revoked_tokens_expires_at"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_index(op.f("ix_account_lockouts_username"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_user_id"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_locked_until"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_is_locked"), table_name="account_lockouts")
    op.drop_table("account_lockouts")
    # ### end Alembic commands ###
