"""align_database_schema_with_models

Revision ID: 7d414c5072e9
Revises: 6a017959a425
Create Date: 2025-09-09 03:33:21.585019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d414c5072e9"
down_revision: Union[str, Sequence[str], None] = "6a017959a425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_lockouts",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique lockout record identifier",
        ),
        sa.Column(
            "user_id", sa.String(length=50), nullable=False, comment="User ID who is locked out"
        ),
        sa.Column(
            "username",
            sa.String(length=100),
            nullable=False,
            comment="Username for quick lookups and audit trail",
        ),
        sa.Column(
            "failed_attempts",
            sa.Integer(),
            nullable=False,
            comment="Current number of consecutive failed login attempts",
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False, comment="Current lockout status"),
        sa.Column(
            "lockout_reason",
            sa.String(length=100),
            nullable=True,
            comment="Reason for lockout (failed_attempts, suspicious_activity, admin_action)",
        ),
        sa.Column(
            "first_failed_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of first failed attempt in current sequence",
        ),
        sa.Column(
            "last_failed_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of most recent failed attempt",
        ),
        sa.Column(
            "locked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when account was locked",
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when lockout expires (NULL for permanent)",
        ),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when account was unlocked",
        ),
        sa.Column(
            "client_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address of failed login attempts",
        ),
        sa.Column(
            "user_agent", sa.Text(), nullable=True, comment="User agent of failed login attempts"
        ),
        sa.Column(
            "unlocked_by",
            sa.String(length=100),
            nullable=True,
            comment="Admin user who unlocked the account manually",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_lockouts_is_locked"), "account_lockouts", ["is_locked"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_locked_until"), "account_lockouts", ["locked_until"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_user_id"), "account_lockouts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_lockouts_username"), "account_lockouts", ["username"], unique=False
    )
    op.create_table(
        "revoked_tokens",
        sa.Column(
            "jti",
            sa.String(length=100),
            nullable=False,
            comment="JWT ID claim - unique identifier for each token",
        ),
        sa.Column(
            "user_id",
            sa.String(length=50),
            nullable=True,
            comment="User who owned the token (for bulk revocation)",
        ),
        sa.Column(
            "token_type",
            sa.String(length=20),
            nullable=False,
            comment="Token type: access, refresh, or reset",
        ),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token was originally issued",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token naturally expires",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When token was revoked",
        ),
        sa.Column(
            "revocation_reason",
            sa.String(length=100),
            nullable=True,
            comment="Reason for revocation: logout, password_change, admin_action, etc.",
        ),
        sa.Column(
            "revoked_by",
            sa.String(length=50),
            nullable=True,
            comment="Who/what revoked the token (user_id, admin_id, or system)",
        ),
        sa.Column(
            "client_ip",
            sa.String(length=45),
            nullable=True,
            comment="IP address when token was revoked",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="User agent when token was revoked",
        ),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_revoked_tokens_expires_at"), "revoked_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_revoked_tokens_user_id"), "revoked_tokens", ["user_id"], unique=False)
    op.create_table(
        "system_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_type", sa.String(length=100), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("string_value", sa.String(length=500), nullable=True),
        sa.Column("json_value", sa.JSON(), nullable=True),
        sa.Column("component", sa.String(length=100), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_metrics_component"), "system_metrics", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_system_metrics_metric_type"), "system_metrics", ["metric_type"], unique=False
    )
    op.create_index(
        op.f("ix_system_metrics_timestamp"), "system_metrics", ["timestamp"], unique=False
    )
    op.create_table(
        "webauthn_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("challenge_key", sa.String(length=255), nullable=False),
        sa.Column("challenge", sa.String(length=1024), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("challenge_type", sa.String(length=50), nullable=False),
        sa.Column("origin", sa.String(length=255), nullable=True),
        sa.Column("rp_id", sa.String(length=255), nullable=True),
        sa.Column("user_verification", sa.String(length=50), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webauthn_challenges_challenge_key"),
        "webauthn_challenges",
        ["challenge_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_challenge_type"),
        "webauthn_challenges",
        ["challenge_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_created_at"),
        "webauthn_challenges",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_expires_at"),
        "webauthn_challenges",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_challenges_user_id"), "webauthn_challenges", ["user_id"], unique=False
    )
    op.create_table(
        "webauthn_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("credential_id", sa.String(length=1024), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=100), nullable=True),
        sa.Column("attestation_object", sa.Text(), nullable=True),
        sa.Column("attestation_format", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("backup_eligible", sa.Boolean(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("registration_ip", sa.String(length=45), nullable=True),
        sa.Column("registration_user_agent", sa.Text(), nullable=True),
        sa.Column("last_used_ip", sa.String(length=45), nullable=True),
        sa.Column("last_used_user_agent", sa.Text(), nullable=True),
        sa.Column("security_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webauthn_credentials_credential_id"),
        "webauthn_credentials",
        ["credential_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_is_active"),
        "webauthn_credentials",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_last_used_at"),
        "webauthn_credentials",
        ["last_used_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_user_id"), "webauthn_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "scraping_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                "CANCELLED",
                "PARTIAL",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("LOW", "NORMAL", "HIGH", "URGENT", name="jobpriority"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("output_directory", sa.String(length=1024), nullable=False),
        sa.Column("custom_slug", sa.String(length=255), nullable=True),
        sa.Column("skip_existing", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("content_size_bytes", sa.Integer(), nullable=True),
        sa.Column("images_downloaded", sa.Integer(), nullable=False),
        sa.Column("converter_config", sa.JSON(), nullable=True),
        sa.Column("processing_options", sa.JSON(), nullable=True),
        sa.Column("archive_path", sa.String(length=1024), nullable=True),
        sa.Column("archive_size_bytes", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scraping_jobs_batch_id"), "scraping_jobs", ["batch_id"], unique=False)
    op.create_index(op.f("ix_scraping_jobs_domain"), "scraping_jobs", ["domain"], unique=False)
    op.create_index(op.f("ix_scraping_jobs_slug"), "scraping_jobs", ["slug"], unique=False)
    op.create_index(op.f("ix_scraping_jobs_status"), "scraping_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_scraping_jobs_url"), "scraping_jobs", ["url"], unique=False)
    op.create_table(
        "content_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("original_html", sa.Text(), nullable=True),
        sa.Column("converted_html", sa.Text(), nullable=True),
        sa.Column("shopify_html", sa.Text(), nullable=True),
        sa.Column("html_file_path", sa.String(length=1024), nullable=True),
        sa.Column("metadata_file_path", sa.String(length=1024), nullable=True),
        sa.Column("images_directory", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("og_title", sa.String(length=500), nullable=True),
        sa.Column("og_description", sa.Text(), nullable=True),
        sa.Column("og_image", sa.String(length=1024), nullable=True),
        sa.Column("twitter_card", sa.String(length=50), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("image_count", sa.Integer(), nullable=True),
        sa.Column("link_count", sa.Integer(), nullable=True),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("conversion_stats", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["scraping_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_results_job_id"), "content_results", ["job_id"], unique=False)
    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=True),
        sa.Column("operation", sa.String(length=100), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("exception_traceback", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scraping_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_logs_job_id"), "job_logs", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_logs_level"), "job_logs", ["level"], unique=False)
    op.drop_index(op.f("idx_audit_created_at"), table_name="audit_log")
    op.drop_index(op.f("idx_audit_entity"), table_name="audit_log")
    op.drop_index(op.f("idx_audit_event_type"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("idx_metrics_job_id"), table_name="metrics")
    op.drop_index(op.f("idx_metrics_labels"), table_name="metrics", postgresql_using="gin")
    op.drop_index(op.f("idx_metrics_name"), table_name="metrics")
    op.drop_index(op.f("idx_metrics_timestamp"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("idx_images_content_id"), table_name="images")
    op.drop_index(op.f("idx_images_downloaded"), table_name="images")
    op.drop_index(op.f("idx_images_original_url"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("idx_cache_expires_at"), table_name="cache")
    op.drop_index(op.f("idx_cache_key"), table_name="cache")
    op.drop_index(op.f("idx_cache_url"), table_name="cache")
    op.drop_table("cache")
    op.drop_index(op.f("idx_content_job_id"), table_name="content")
    op.drop_index(op.f("idx_content_json"), table_name="content", postgresql_using="gin")
    op.drop_index(op.f("idx_content_published_at"), table_name="content")
    op.drop_index(op.f("idx_content_search"), table_name="content", postgresql_using="gin")
    op.drop_index(op.f("idx_content_shopify_handle"), table_name="content")
    op.drop_index(op.f("idx_content_slug"), table_name="content")
    op.drop_index(op.f("idx_content_title"), table_name="content")
    op.drop_index(op.f("idx_content_wordpress_id"), table_name="content")
    op.drop_table("content")
    op.drop_index(op.f("idx_jobs_batch_id"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_created_at"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_metadata"), table_name="jobs", postgresql_using="gin")
    op.drop_index(op.f("idx_jobs_source_url"), table_name="jobs")
    op.drop_index(op.f("idx_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.add_column("batches", sa.Column("max_concurrent", sa.Integer(), nullable=False))
    op.add_column("batches", sa.Column("continue_on_error", sa.Boolean(), nullable=False))
    op.add_column(
        "batches", sa.Column("output_base_directory", sa.String(length=1024), nullable=False)
    )
    op.add_column("batches", sa.Column("create_archives", sa.Boolean(), nullable=False))
    op.add_column("batches", sa.Column("cleanup_after_archive", sa.Boolean(), nullable=False))
    op.add_column("batches", sa.Column("skipped_jobs", sa.Integer(), nullable=False))
    op.add_column("batches", sa.Column("summary_data", sa.JSON(), nullable=True))
    op.add_column("batches", sa.Column("batch_config", sa.JSON(), nullable=True))
    op.alter_column(
        "batches",
        "id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.alter_column(
        "batches",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "processing", "completed", "failed", "cancelled", name="job_status"
        ),
        server_default=None,
        type_=postgresql.ENUM(
            "PENDING",
            "RUNNING",
            "COMPLETED",
            "FAILED",
            "SKIPPED",
            "CANCELLED",
            "PARTIAL",
            name="jobstatus",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "batches",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "batches", "total_jobs", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.alter_column(
        "batches", "completed_jobs", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.alter_column(
        "batches", "failed_jobs", existing_type=sa.INTEGER(), server_default=None, nullable=False
    )
    op.drop_index(op.f("idx_batches_created_at"), table_name="batches")
    op.drop_index(op.f("idx_batches_status"), table_name="batches")
    op.create_index(op.f("ix_batches_status"), "batches", ["status"], unique=False)
    op.drop_column("batches", "options")
    op.drop_column("batches", "updated_at")
    op.drop_column("batches", "concurrent_limit")
    op.drop_column("batches", "statistics")
    op.drop_column("batches", "rate_limit_per_second")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches",
        sa.Column(
            "rate_limit_per_second",
            sa.INTEGER(),
            server_default=sa.text("10"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "concurrent_limit",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_batches_status"), table_name="batches")
    op.create_index(op.f("idx_batches_status"), "batches", ["status"], unique=False)
    op.create_index(
        op.f("idx_batches_created_at"),
        "batches",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "batches",
        "failed_jobs",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
    )
    op.alter_column(
        "batches",
        "completed_jobs",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
    )
    op.alter_column(
        "batches",
        "total_jobs",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
    )
    op.alter_column(
        "batches",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=True,
    )
    op.alter_column(
        "batches",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "RUNNING",
            "COMPLETED",
            "FAILED",
            "SKIPPED",
            "CANCELLED",
            "PARTIAL",
            name="jobstatus",
        ),
        server_default=sa.text("'pending'::job_status"),
        type_=postgresql.ENUM(
            "pending", "processing", "completed", "failed", "cancelled", name="job_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "batches",
        "id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.drop_column("batches", "batch_config")
    op.drop_column("batches", "summary_data")
    op.drop_column("batches", "skipped_jobs")
    op.drop_column("batches", "cleanup_after_archive")
    op.drop_column("batches", "create_archives")
    op.drop_column("batches", "output_base_directory")
    op.drop_column("batches", "continue_on_error")
    op.drop_column("batches", "max_concurrent")
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "job_type",
            postgresql.ENUM("single", "batch", "scheduled", name="job_type"),
            server_default=sa.text("'single'::job_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "processing", "completed", "failed", "cancelled", name="job_status"
            ),
            server_default=sa.text("'pending'::job_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "target_format",
            postgresql.ENUM("html", "json", "markdown", "csv", name="export_format"),
            server_default=sa.text("'html'::export_format"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "retry_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_retries",
            sa.INTEGER(),
            server_default=sa.text("3"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("processing_time_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("download_size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("output_size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("batch_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.CheckConstraint("priority >= 1 AND priority <= 10", name="jobs_priority_check"),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name="jobs_batch_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="jobs_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("idx_jobs_source_url"), "jobs", ["source_url"], unique=False)
    op.create_index(
        op.f("idx_jobs_metadata"), "jobs", ["metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_jobs_created_at"), "jobs", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(op.f("idx_jobs_batch_id"), "jobs", ["batch_id"], unique=False)
    op.create_table(
        "content",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "content_type",
            postgresql.ENUM("wordpress", "shopify", "generic", name="content_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("html_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("markdown_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "json_content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("meta_title", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("meta_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("meta_keywords", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column("wordpress_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "wordpress_categories", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "wordpress_tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.Column("wordpress_author", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("shopify_handle", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "shopify_template_suffix", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "shopify_published",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="content_job_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="content_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_content_wordpress_id"), "content", ["wordpress_id"], unique=False)
    op.create_index(op.f("idx_content_title"), "content", ["title"], unique=False)
    op.create_index(op.f("idx_content_slug"), "content", ["slug"], unique=False)
    op.create_index(op.f("idx_content_shopify_handle"), "content", ["shopify_handle"], unique=False)
    op.create_index(
        op.f("idx_content_search"),
        "content",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(html_content, ''::text))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_content_published_at"),
        "content",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_content_json"), "content", ["json_content"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("idx_content_job_id"), "content", ["job_id"], unique=False)
    op.create_table(
        "cache",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("cache_key", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("cache_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "headers", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hit_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_accessed",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cache_pkey")),
        sa.UniqueConstraint(
            "cache_key",
            name=op.f("cache_cache_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_cache_url"), "cache", ["url"], unique=False)
    op.create_index(op.f("idx_cache_key"), "cache", ["cache_key"], unique=False)
    op.create_index(op.f("idx_cache_expires_at"), "cache", ["expires_at"], unique=False)
    op.create_table(
        "images",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("original_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("local_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("cdn_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("mime_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("width", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("height", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("alt_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("caption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "downloaded",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "optimized",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.id"], name=op.f("images_content_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("images_pkey")),
    )
    op.create_index(op.f("idx_images_original_url"), "images", ["original_url"], unique=False)
    op.create_index(op.f("idx_images_downloaded"), "images", ["downloaded"], unique=False)
    op.create_index(op.f("idx_images_content_id"), "images", ["content_id"], unique=False)
    op.create_table(
        "metrics",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("metric_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("metric_value", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("metric_unit", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("batch_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("metrics_batch_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("metrics_job_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("metrics_pkey")),
    )
    op.create_index(
        op.f("idx_metrics_timestamp"),
        "metrics",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_metrics_name"), "metrics", ["metric_name"], unique=False)
    op.create_index(
        op.f("idx_metrics_labels"), "metrics", ["labels"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("idx_metrics_job_id"), "metrics", ["job_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("event_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("entity_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("ip_address", postgresql.INET(), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("audit_log_pkey")),
    )
    op.create_index(op.f("idx_audit_event_type"), "audit_log", ["event_type"], unique=False)
    op.create_index(
        op.f("idx_audit_entity"), "audit_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("idx_audit_created_at"),
        "audit_log",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_job_logs_level"), table_name="job_logs")
    op.drop_index(op.f("ix_job_logs_job_id"), table_name="job_logs")
    op.drop_table("job_logs")
    op.drop_index(op.f("ix_content_results_job_id"), table_name="content_results")
    op.drop_table("content_results")
    op.drop_index(op.f("ix_scraping_jobs_url"), table_name="scraping_jobs")
    op.drop_index(op.f("ix_scraping_jobs_status"), table_name="scraping_jobs")
    op.drop_index(op.f("ix_scraping_jobs_slug"), table_name="scraping_jobs")
    op.drop_index(op.f("ix_scraping_jobs_domain"), table_name="scraping_jobs")
    op.drop_index(op.f("ix_scraping_jobs_batch_id"), table_name="scraping_jobs")
    op.drop_table("scraping_jobs")
    op.drop_index(op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_last_used_at"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_is_active"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_credential_id"), table_name="webauthn_credentials")
    op.drop_table("webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_challenges_user_id"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_expires_at"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_created_at"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_challenge_type"), table_name="webauthn_challenges")
    op.drop_index(op.f("ix_webauthn_challenges_challenge_key"), table_name="webauthn_challenges")
    op.drop_table("webauthn_challenges")
    op.drop_index(op.f("ix_system_metrics_timestamp"), table_name="system_metrics")
    op.drop_index(op.f("ix_system_metrics_metric_type"), table_name="system_metrics")
    op.drop_index(op.f("ix_system_metrics_component"), table_name="system_metrics")
    op.drop_table("system_metrics")
    op.drop_index(op.f("ix_revoked_tokens_user_id"), table_name="revoked_tokens")
    op.drop_index(op.f("ix_revoked_tokens_expires_at"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_index(op.f("ix_account_lockouts_username"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_user_id"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_locked_until"), table_name="account_lockouts")
    op.drop_index(op.f("ix_account_lockouts_is_locked"), table_name="account_lockouts")
    op.drop_table("account_lockouts")
    # ### end Alembic commands ###
